[Bash] Fix coloring of final symbol

diff --git a/dotfiles/bash_prompt b/dotfiles/bash_prompt
--- a/dotfiles/bash_prompt
+++ b/dotfiles/bash_prompt
@@ -21,13 +21,15 @@ GIT_PS1_SHOWUNTRACKEDFILES=1
 
 
 prompt() {
+    # Checking the return value must happen first, otherwise it will be
+    # overwritten by the other commands in this function.
+    local retval="$?"
+
     # If this is a TRAMP session, then use an exceedingly simple prompt.
     if [[ "$INSIDE_EMACS" == *"tramp"* ]]; then
         PS1='\$'
         return
     fi
-
-    local retval="$?"
 
     local -A colors
     # Color of the project indicator in the prompt.
